layout_spectrum: 0.3960573
color:
  saturation: 0.1907138
  lightness: 0.5920045
  brandStrength: 0.7096774
  brandColors:
    - '#B4B4B4'
    - '#545454'
    - '#1F1F1F'
  rhythmicContrast: 0.8064516
typography_spectrum: 0.530466
name: 'Stephen McKissen '
